networks:
 expense: {}
 # docker volume create mysql
volumes:
 mysql:
services:
  backend:
    image: balaguru20/backend:1.0.0
    #backend trying to connect mysql, before it is completely up, so we need to delay few sec
    command: sh -c "sleep 10 && node /opt/backend/index.js"
    networks:
    - expense
    container_name: backend
    depends_on:
    - mysql
    
  # docker run -d --name mysql --network expense -v mysql:var/lib/mysql mysql:1.0.0
  mysql:
    image: balaguru20/mysql:1.0.0
    networks:
    - expense
    container_name: mysql
    volumes:
    - mysql:/var/lib/mysql

  frontend:
    image: balaguru20/frontend:1.0.0
    networks:
    - expense
    container_name: frontend
    ports:
    - 80:80
    depends_on:
    - backend
      